[build]
builder = "Dockerfile"
buildCommand = "npm install"

[deploy]
startCommand = "node main.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
MONGODB_URI = "mongodb+srv://alemancheck:ALEMAN1988@cluster0.er1x4.mongodb.net/alemanChecker?retryWrites=true&w=majority&appName=Cluster0"
NODE_ENV = "production"
PORT = "3000"
ADMIN_KEY = "ALEMAN2024"
TELEGRAM_TOKEN = "7461272757:AAEXQIGLnP9rEsLc2VAFahLZrPB9tjsasF0"
TELEGRAM_CHAT_ID = "6912929677"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
CHROME_BIN = "/usr/bin/google-chrome"