services:
  - type: web
    name: OrishaChecker
    env: node
    buildCommand: npm install --production
    startCommand: node main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false
      - key: DOMAIN
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
    healthCheckPath: /health
    disk:
      name: checker-data
      mountPath: /app/cards
      sizeGB: 1
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - main.js
        - models/**/*.js
        - utils.js
        - logger.js
        - ElegbaGate.js
        - OshunGate.js
        - health.js
        - public/**/*
        - assets/**/*