services:
  - type: web
    name: OrishaChecker
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: DOMAIN
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    buildpacks:
      - url: heroku/nodejs
      - url: https://github.com/heroku/heroku-buildpack-google-chrome
    healthCheckPath: /health
    disk:
      name: checker-data
      mountPath: /app/cards
      sizeGB: 1