services:
  - type: web
    name: OrishaChecker
    env: node
    buildCommand: npm install
    startCommand: node main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false
      - key: DOMAIN
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    disk:
      name: checker-data
      mountPath: /app/cards
      sizeGB: 1